# Generated by Django 3.0.8 on 2020-07-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acm_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='CheckList',
        ),
    ]
