# Generated by Django 3.0.8 on 2020-07-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm_api', '0003_grocerylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
