# Generated by Django 3.0.8 on 2020-07-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm_api', '0005_remove_grocerylist_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='text',
            field=models.Field(default=''),
        ),
    ]
