# Generated by Django 3.0.8 on 2020-07-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acm_api', '0006_grocerylist_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='text',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='items',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='acm_api.CheckList'),
        ),
    ]
