# Generated by Django 3.0.8 on 2020-07-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm_api', '0007_auto_20200728_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='text',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
