# Generated by Django 3.0.8 on 2020-07-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm_api', '0012_remove_grocerylist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='text',
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
