# Generated by Django 3.0.8 on 2020-07-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm_api', '0013_auto_20200728_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='items',
            field=models.Field(default=''),
        ),
    ]
