# Generated by Django 3.0.8 on 2020-07-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acm_api', '0014_grocerylist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='items',
        ),
    ]
