# Generated by Django 3.0.8 on 2020-07-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acm_api', '0015_remove_grocerylist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
