# Generated by Django 3.0.8 on 2020-07-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acm_api', '0017_auto_20200728_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='g_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='acm_api.GroceryList'),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='items',
            field=models.Field(default=''),
        ),
    ]
