# Generated by Django 3.0.8 on 2020-07-28 07:56

from django.db import migrations, models
import rest_framework.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acm_api', '0019_remove_grocerylist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='items',
            field=models.Field(default=[], serialize=rest_framework.fields.ListField),
        ),
    ]
